SECRET_KEY = 'dev'
SQLALCHEMY_DATABASE_URI = 'sqlite:///../testing/test.db'
TESTING = True
DEBUG = False
WTF_CSRF_ENABLED = False
OAUTH_ID = 'dVqFPnPR0uljNdieqnlPQ'
OAUTH_SECRET = 'zSqdnIN8uPGIcYiUFDtqTxmQ7ZHQjKYG'
SQLALCHEMY_TRACK_MODIFICATIONS = False
