SECRET_KEY = 'dev'
FLASK_ENV = 'development'
WTF_CSRF_ENABLED = False
OAUTH_ID = 'dVqFPnPR0uljNdieqnlPQ'
OAUTH_SECRET = 'zSqdnIN8uPGIcYiUFDtqTxmQ7ZHQjKYG'
SQLALCHEMY_DATABASE_URI = "sqlite:///../testing/test.db"
SQLALCHEMY_TRACK_MODIFICATIONS = False
TESTING = True
